version: "3"

services:
  db:
    container_name: my_db
    image: mariadb
    volumes:
      - dbnuevo:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: full4kroot
      MYSQL_DATABASE: midb
      MYSQL_USER: midb
      MYSQL_PASSWORD: midb
      MYSQL_DATABASE: midb

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: proxy_filedocker
    image: wordpress-imagen
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
      - "20:20"
      - "21:21"
      - "40000:40000"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/httpd/conf.d/:/etc/httpd/conf.d/
      - /var/www/html/:/var/www/html/

volumes:
  dbnuevo:
